import LyricLines from "./LyricLines";
import LyricTimeLines from "./LyricTimeLines";

import TextFileParser from "./TextFileParser";

export const lyric_lines =  new LyricLines(
	// new TextFileParser("Last November strikes me like a gone train\nYou took my hand in the pouring rain\nKept looking back at me\nThis November feels a little different\nThe rain is still pouring, went straight down the drain\nWalking home alone with a bottle of champaign\nquarter after 10\nI won't be needing your hand\nThe only thing left to erase\nIs the tattoo above my heart\nThe last trace\nIt's perfectly faked\n1.5 mm under your skin\nIs that how deep our love has gotten to you?\nYou wear my heart right beneath your right sleeve\nIs that how you're planning to remember me?\nCuz I don't appreciate it like you do\nCuz I don't appreciate it like you do\n1.5 mm under my skin\nThis is where I plan to remove you\n\nLast summer felt like a waking dream\nOur love left a scar way too extreme\nWas it perfect as it seemed\nNow Everything's turned into hallucination\nCan it be a celebration\nHere's to my funny-looking tattoo\nWalking home alone with a bottle of champaign\nquarter after 10\nI won't be needing your hand\nThe only thing left to erase\nIs the tattoo above my heart\nThe last trace\nI wish it was fake\n1.5 mm under your skin\nIs that how deep our love has gotten to you?\nYou wear my heart right beneath your right sleeve\nIs that how you're planning to remember me?\nCuz I don't appreciate it like you do\nCuz I don't appreciate it like you do\n1.5 mm under my skin\nThis is where I plan to remove you\n\n1.5 mm under your skin\n\n1.5 mm under my skin\nYou wear my heart right beneath your right sleeve\nIs that how you're planning to remember me?\n\nCuz I don't appreciate it like you do\n1.5 mm under my skin\nThis is where I plan to remove you")
	// new TextFileParser("Last November strikes me like a gone train\nYou took my hand in the pouring rain\nKept looking back at me")
	new TextFileParser("I get up in the evening\nand I ain't got nothing to say\nI come home in the morning\nI go to bed feeling the same way\nI ain't nothing but tired\nMan I'm just tired and bored with myself\nHey there baby, I could use just a little bit of help\n\nYou can't start a fire\nYou can't start a fire without a spark\nThis gun's for hire\neven if we're just dancing in the dark\n\nMessage keeps getting clearer\nradio's on and I'm moving 'round the place\nI check my look in the mirror\nI wanna change my clothes, my hair, my face\nMan I ain't getting nowhere\nI'm just living in a dump like this\nThere's something happening somewhere\nbaby I just know that there is\n\nYou can't start a fire\nYou can't start a fire without a spark\nThis gun's for hire\neven if we're just dancing in the dark\n\nYou sit around getting older\nthere's a joke here somewhere and it's on me\nI'll shake this world off my shoulders\ncome on baby this laugh's on me\n\nStay on the streets of this town\nand they'll be carving you up alright\nThey say you gotta stay hungry\nhey baby I'm just about starving tonight\nI'm dying for some action\nI'm sick of sitting 'round here trying to write this book\nI need a love reaction\ncome on now baby gimme just one look\n\nYou can't start a fire sitting 'round crying over a broken heart\nThis gun's for hire\neven if we're just dancing in the dark\n\nYou can't start a fire worrying about your little world falling apart\nThis gun's for hire\nEven if we're just dancing in the dark\ndancing in the dark\nin the dark~")
	.getParsedLine(),
	{
		createDate: new Date(),
		songName: "1.5mm"
	}
);

export const lyric_time_lines = new LyricTimeLines(
	["___PRE_LINE___", "I get up in the evening","and I ain't got nothing to say","I come home in the morning","I go to bed feeling the same way","I ain't nothing but tired","Man I'm just tired and bored with myself","Hey there baby, I could use just a little bit of help","","You can't start a fire","You can't start a fire without a spark","This gun's for hire","even if we're just dancing in the dark","","Message keeps getting clearer","radio's on and I'm moving 'round the place","I check my look in the mirror","I wanna change my clothes, my hair, my face","Man I ain't getting nowhere","I'm just living in a dump like this","There's something happening somewhere","baby I just know that there is","","You can't start a fire","You can't start a fire without a spark","This gun's for hire","even if we're just dancing in the dark","","You sit around getting older","there's a joke here somewhere and it's on me","I'll shake this world off my shoulders","come on baby this laugh's on me","","Stay on the streets of this town","and they'll be carving you up alright","They say you gotta stay hungry","hey baby I'm just about starving tonight","I'm dying for some action","I'm sick of sitting 'round here trying to write this book","I need a love reaction","come on now baby gimme just one look","","You can't start a fire sitting 'round crying over a broken heart","This gun's for hire","even if we're just dancing in the dark","","You can't start a fire worrying about your little world falling apart","This gun's for hire","Even if we're just dancing in the dark","dancing in the dark","in the dark~","___END_LINE___"],
	[19617,24222,27002,31056,34061,38671,43322,50413,65247,68848,72901,76591,81376,95777,99480,103107,106960,110831,114719,118481,122470,125703,125983,129846,133775,137621,142443,156537,159535,164096,167170,171718,171961,175847,179277,183256,187002,190947,194681,198529,202243,202483,210056,213792,217358,217572,225328,229078,238538,247435,249779],
	-250
);